# Naive Bayes

## Bernauli NB

In [11]:
from sklearn.naive_bayes import BernoulliNB
import numpy as np

x = np.random.randint(2, size=(6,100)) # like one hot encoding of 100 features
x1 = np.random.randint(2, size=(2,100))  #test set
y = np.array([1,2,3,3,4,5])    #class labels
print(x)
print(y)


# make model
clf = BernoulliNB()  # with default
print(clf)

#train model
clf.fit(x,y)

#
print("x1",x1)

#predict
clf.predict(x1)

[[0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1
  0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1
  1 1 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 0 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0
  0 0 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1
  0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1]
 [0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0
  1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0
  0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0]
 [1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1 0
  0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0
  1 1 1 1 0 0 1 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 0]
 [0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1
  1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1
  0 1 0 0 1 1 1 1 0 0 1 

array([2, 2])

## MultinomialNB

In [13]:
from sklearn.naive_bayes import MultinomialNB
X1 = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

clf = MultinomialNB()
print(clf)
clf.fit(x, y)

print(clf.predict(X1)) # predicted class

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
[4 3 5 6 2 1]


## Gaussian Naive Bayes

In [27]:
from sklearn.naive_bayes import GaussianNB

x11 = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
y11 = np.array([1, 1, 1, 2, 2, 2])

print(x11, '\n', y11)

#make model
clf = GaussianNB()
print(clf)

#train model
clf.fit(x11, y11)

print(clf.predict([[-0.8, -1]]))

clf_pf = GaussianNB()
clf_pf.partial_fit(x11, y11, np.unique(y11))

print(clf_pf.predict([[.1, 1]]))


[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]] 
 [1 1 1 2 2 2]
GaussianNB(priors=None)
[1]
[2]


# to do

## Gaussian Naive Bayes with SciKit Learn over iris data set

In [28]:
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import seaborn as sns

# Gaussian Naive Bayes
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [29]:
# load the iris datasets
iris = datasets.load_iris()

# Grab features (X) and the Target (Y)
X = iris.data

Y = iris.target

# Show the Built-in Data Description
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

Since we have already done a general analysis of this data in earlier lectures many times over this dataset, let's go ahead and move on to using the Naive Bayes Method to seperate this data set into multiple classes.

In [30]:
# Fit a Naive Bayes model to the data
model = GaussianNB()

In [36]:
from sklearn.model_selection import train_test_split
# Split the data into Trainging and Testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.25)

In [37]:
# Fit the training model
model.fit(X_train,Y_train)

GaussianNB(priors=None)

In [38]:
# Predicted outcomes
predicted = model.predict(X_test)



In [39]:
print(metrics.accuracy_score(Y_test, predicted))
print(metrics.pre(Y_test, predicted))
print(metrics.accuracy_score(Y_test, predicted))
print(metrics.accuracy_score(Y_test, predicted))

0.9210526315789473
